openapi: 3.0.0
info:
  title: tianmiantech/WeFe
  version: 1.0.0
  description: tianmiantech/WeFe
servers:
- url: http://localhost:8080
  description: Local development server
paths:
  /data_output_info/model_export:
    all:
      tags:
      - ModelExportController
      summary: download
      description: ''
      operationId: board-service_com.welab.wefe.board.service.api.data_output_info.ModelExportController#download
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
      deprecated: false
  /download:
    get:
      tags:
      - BaseController
      summary: download
      description: ''
      operationId: common-web_com.welab.wefe.common.web.controller.BaseController#download
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
      deprecated: false
  /**:
    get:
      tags:
      - BaseController
      summary: get
      description: ''
      operationId: common-web_com.welab.wefe.common.web.controller.BaseController#get
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
      deprecated: false
    post:
      tags:
      - BaseController
      summary: post
      description: ''
      operationId: common-web_com.welab.wefe.common.web.controller.BaseController#post
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
      deprecated: false
components: {}
